### ISSUE TITLE
More button doesn't respond as expected

### ISSUE THREAD

**Issue by henkvancann** [BlockchainCommons/GordianSeedTool-iOS#107]
MacOS Montgomery Ipad versus of TestFlight GST 1.3 (build 42)

Seed -> Cosigner -> share as Crypto-HDkey -> More

More button doesn't respond as expected. I expect a pop-up with choices, for example for Signal

The other four menu choices above 'More...' do pop-up the right application.

<img width="233" alt="Screenshot 2021-12-19 at 13 53 14" src="https://user-images.githubusercontent.com/479356/146675609-e6791158-8c03-4340-a793-177a15148ea1.png">
<img width="985" alt="Screenshot 2021-12-19 at 13 51 45" src="https://user-images.githubusercontent.com/479356/146675611-7ffe0e65-afd7-4ed0-97e4-92bede590939.png">

**Comment by wolfmcnally** [comment]
Please re-test.

**Comment by henkvancann** [comment]
Done, issue persists.
