### ISSUE TITLE
MANUAL text should become available in app?

### ISSUE THREAD

**Issue by henkvancann** [BlockchainCommons/GordianSeedTool-iOS#108]
I experienced using the die rolls or cards that I'd like to have context help, especially when it comes to entropy (want to feel safe)

Example  _> https://github.com/henkvancann/GordianSeedTool-iOS/blob/master/Docs/MANUAL.md#creating-a-seed.

```text
The coin flipping, die rolling, and card drawing methods all have three buttons at the bottom, which 
allow you to: erase one entry (back arrow); use the randomizer to add one entry (a die with a "1");
 or use the randomizer to add all of the entries (a die with an "all").
```

Suggestion 1 : context "i" that delivers this information in app.

Suggestion 2: Rename "playing" cards to "flipping" or "drawing" or "tossing" cards. Playing cards suggests that there is more magic happening (a game ) than just flipping / deleting a random card. Which is not the case.
Suggestion 3: 
"Our card draw technique is not identical to his." [here](https://github.com/henkvancann/GordianSeedTool-iOS/blob/master/Docs/MANUAL.md#creating-a-seed.) is not very confidence-building. I need to trust. Don't trust, verify. Give us this capability by being very specific how it's done.

**Comment by wolfmcnally** [comment]
"Playing Card" is not a verb, it is a noun. https://en.wikipedia.org/wiki/Playing_card

**Comment by henkvancann** [comment]
Right, I confused 'play cards' with 'playing card'. Non-native speaker problem ;)

**Comment by wolfmcnally** [comment]
> Non-native speaker problem

At some point perhaps we'll prioritize internationalization and localization. 😄
