### ISSUE TITLE
Make it possible to copy to clipboard from share on macOS.

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianSeedTool-iOS#113]
macOS 12.1, SeedTool 1.3 (42):

Click on Authenticate, click on Share:

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/69103/147845296-3487e26b-5be4-484f-a2b9-a72ed43c8be9.png">

Click on BIP39:

<img width="165" alt="image" src="https://user-images.githubusercontent.com/69103/147845288-b0b0877d-835e-4d12-856c-39604f73365f.png">

Two bugs: 1) the share menu show up outside of the application window not near the cursor, and 2) has no copy to clipboard choice:

<img width="298" alt="image" src="https://user-images.githubusercontent.com/69103/147845313-996adc58-5f79-4ae8-a91d-dcd032f4e29b.png">

**Comment by wolfmcnally** [comment]
As this is actually a shortcoming in the share sheet implementation of macOS, I am re-classifying this as a feature request.

**Comment by wolfmcnally** [comment]
This has been fixed in the latest beta release 1.3.3 (48).
