### ISSUE TITLE
When responding to key requests, describe important kinds of derivations

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianSeedTool-iOS#114]
When a request is made for keys with common derivations, Seed Tool should say more. 

For instance with this `crypto-request`: 

<img width="959" alt="94F400FC-E145-491D-A03B-CC5BBFC6C7DA" src="https://user-images.githubusercontent.com/69103/147991204-520e4c42-0a87-4613-821f-27f1cc31930a.png">

the current first screen is:

![E63AF1F6-F222-4B7C-943C-739FCC1BD304](https://user-images.githubusercontent.com/69103/147991234-36d75c11-64e8-4d0a-8c62-a38d0a870f85.png)

This screen should probably say that this is likely a request to participate in a segwit multisig account, as one of multiple other keys from others. (Exact language for review by @ShannonA).

**Comment by wolfmcnally** [comment]
@ChristopherA @shannona Please add a list of the derivations and the annotations you would like SeedTool to display with them.

**Comment by ChristopherA** [comment]
You'll need to coordinate with other members of BC community on about the edge cases. @Fonta1n3 I think tests over 40 with Fully Noded, and recovery should support all of them. Base line are current recommended, which are segwt, nested-segwit, and cosigner 48.,legacy is bitcoin-core hd, electrum legacy (which I think handles change differently), legacy P2PKH (with a variant that I think Bred wallet used)) BIP44 & 45. Then there is the future, which single key taproot is the the most important.

Long-term I hope all of these go away in favor of just exchange of descriptors.

**Comment by wolfmcnally** [comment]
@Fonta1n3, is there a source of truth you use for the derivations you support, or a document you've produced yourself that I can refer to?

**Comment by ChristopherA** [comment]
Two different issues here:

In the Key Request pane, it should say what this derivation is for (segwit xpub, co-signer xpub, etc.) if it is a known derivation, and otherwise should give a strong warning if it is for an unknown coin, and a lesser warning if we know the coin, but it we don't know what the child derivation is used for.

I really would like this for our list current small list of standard types for the 1.4 release.

The second issue is that there is larger list of known derivations, that at some release (1.6?) we should support, and do more detail on warning.

**Comment by wolfmcnally** [comment]
Rescoping for 1.4 to adding the long name (or unknown) to the Key Request screen.

**Comment by wolfmcnally** [comment]
This should be addressed in the next beta.

**Comment by shannona** [comment]
@wolfmcnally as of 54, I'm not seeing a description.

![IMG_2867](https://user-images.githubusercontent.com/1110886/157300154-0c069f0a-e79e-4126-9324-5bf54f385c8a.jpeg)

**Comment by shannona** [comment]
Now showing those details:

![IMG_3213](https://user-images.githubusercontent.com/1110886/167730346-f2c0f10e-5e90-4154-a9bb-27209430dc5f.jpeg)
