### ISSUE TITLE
FEATURE REQUEST: Button to move to animated form

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianSeedTool-iOS#115]
In testing with Sparrow Wallet's QR reader on my Intel Mac and my iPhone with Seed Tool, `crypto-account` QR is largely failing to import as it seems too large for the low-res camera on that model of the Mac:

<img width="758" alt="image" src="https://user-images.githubusercontent.com/69103/147993889-9002e969-c88f-4a0e-a548-b4b35e84e305.png">

This will be even worse with my old MacBook Air with wifi card removed which I use for offline testing.

In an old version of Gordian Wallet, there was a small button at bottom of almost all QRs presenting URs which would switch it to UR animate mode. This might be a solution to this problem when a large QR fails. I'm not sure if anyone else supports animated QR for anything but PSBTs, but we probably should for our reference.

/cc @craigraw @shannona

**Comment by wolfmcnally** [comment]
Closing. Please open a new issue if the problem persists.
