### ISSUE TITLE
UX: Auto-fill today's date

### ISSUE THREAD

**Issue by jblachly** [BlockchainCommons/GordianSeedTool-iOS#127]
When adding a new seed, the "Creation Date" field is left blank by default. When clicking the empty field, it does auto-insert today's date.

However, in the following workflows, it should automatically insert today's date, so the user does not forget:

1. Quick create
2. Coin flips
3. Die Rolls
4. Playing cards

In the import existing seeds workflows, I agree it should remain blank by default.

**Comment by ChristopherA** [comment]
This seems to be a quite reasonable, and modest change. I'll add it to the enhancements list.

I don't know if it will make it into the release we are testing right now (1.4), and we have a project behind that version that we need to get back to, but if it is doesn't get slipped in it sooner should be in 1.4.1 or 1.5.
