### ISSUE TITLE
Seed Tool - Cosigner Public Key detail popup screen - 'Done' won't work

### ISSUE THREAD

**Issue by henkvancann** [BlockchainCommons/GordianSeedTool-iOS#128]
Version 47 of Seed Tool. I am on iPhone 7 iOS 15.2.

When I choose Cosigner Public Key, I get the detail popup screen. When I try to send that away with 'Done' button, it won't work.

I can get rid of the pop-up by swiping it away.

<img width="375" alt="signal-2022-02-16-180250" src="https://user-images.githubusercontent.com/479356/154322141-492a5c8f-9a9b-4d9c-8ef5-c5cc4e6b5750.png">

**Comment by wolfmcnally** [comment]
I was also unable to reproduce this under iOS 15.3.1 and SeedTool 1.3.3 (beta 48).

**Comment by henkvancann** [comment]
the problem persists SeedTool 1.3.3 (beta 53).

**Comment by wolfmcnally** [comment]
I'll reopen this and see whether there's anything else I can do about it.

**Comment by wolfmcnally** [comment]
I finally did reproduce this while testing on our new iPad Mini.
