### ISSUE TITLE
Can't Share QR of Address

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianSeedTool-iOS#139]
There is no long-hold feature to share the address QR from the address subpage of the Key Export page.

**Comment by wolfmcnally** [comment]
Currently Seed Tool does not display any QR codes that do not contain URs, owing to the (original but apparently changing) nature of Seed Tool as primarily a reference app. If this becomes a requirement, it should be prioritized as a feature request.

**Comment by ChristopherA** [comment]
As the first QRs for bitcoin were addresses, and almost every wallet supports them, we should support them as output. 

I do agree it is a feature for a future release, so keeping it open.

**Comment by shannona** [comment]
The public key & address can be output as a secondary derivation from a Master Key. If we think it's appropriate for addresses to be output anywhere else, that should be a new Issue/enhancement.

The QR now outputs as a a share, so leaving this closed seems appropriate, as the original bug/enhancement is resolved.
