### ISSUE TITLE
Can't Share QR of Ethereum Private Key

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianSeedTool-iOS#140]
The Ethereum Private Key QR also doesn't long-hold to save.

**Comment by ChristopherA** [comment]
I believe that ETH wallets also support sending to an address in a QR. reopening for further investigation.

**Comment by wolfmcnally** [comment]
That is a separate issue. I fixed the issue that this was opened for.

**Comment by ChristopherA** [comment]
If you are going to do that don’t close that issue until you have created the new issue, tagged it and milestones appropriately, and linked separate issue here. Then you can close.

I don’t want to have to search closed issues.

reopening

**Comment by shannona** [comment]
Verified QR of Ethereum Private Key now shares.

Verified QR of Ethereum address shares.

I think that's everything, @ChristopherA (Addresses were discussed in a different Issue), but if not please re-open and let me know what I'm missing.
