### ISSUE TITLE
Base58 Export Missing from Cosigner Public/Private Key Buttons

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianSeedTool-iOS#148]
If you export a Cosigner Public or Private Key using the specialized buttons, you're only allowed to "share as ur:crypto-hdkey" or "print" (the UR) or share the QR (or the UR).

If you "Derive Key"->"Other Key Derivation" for any Derivation, including Cosigner, you're given an extra option of "Share as Base58".

The "Share as Base58" option should be added to the individual Cosigner Public & Private Key buttons for consistency (and generally, I'd suggest just use the same page if possible, because other less important things, such as the developer-test buttons, are also missing.

**Comment by ChristopherA** [comment]
Though it is not critical, I’d like to see this fixed in 1.4.

**Comment by wolfmcnally** [comment]
This should be fixed in the next beta release. Please retest.

**Comment by shannona** [comment]
Verified for pub and prv keys. Thanks.
