### ISSUE TITLE
Suggestion for Change to Key Derivation (i)nfo Text

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianSeedTool-iOS#150]
There are a number of examples in "What is Key Derivation" that refer to 48'/0'/0'/0, which turns out to be the largely ignored Legacy Multisig Cosigner. (The older 45' was never superseded, I presume because Segwit came along).

I'd suggest changing these to 48'/0'/0'/2' for better correlation with the actual app.

**Comment by wolfmcnally** [comment]
May I suggest you make these changes? It is in the markdown file here: https://github.com/BlockchainCommons/GordianSeedTool-iOS/blob/master/SeedTool/Markdown/what-is-key-derivation.md

**Comment by shannona** [comment]
Is here:
https://github.com/BlockchainCommons/GordianSeedTool-iOS/pull/155

**Comment by wolfmcnally** [comment]
Merged.
