### ISSUE TITLE
UX: Need for Undo or how X/Cancel function in Seed Name Editing

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianSeedTool-iOS#152]
Using SeedTool Version 1.4 (54)

Twice now (once on iOS and once on macOS) while editing a seed's Name, I have accidently clicked on the dice button. 

The reason why this happens is that the Name field is a single line, and has … at end when the text is too long, so you have to tap the end of the line to get to the end of the text to append to it or edit what you have that is past the … — this often results in accidentally tapping the dice button, which replaces the whole name.

If you try to tap the field to reveal the undo, you can't. On macOS if you command-Z it does not undo. If you click on the X it just deletes the line, and does not undo. You also can't cancel elsewhere in the to restore back to the original.

Some thoughts in addition to puzzling out how to enable undo:

* The edit Name field maybe should not be compressed … at the end, but at the middle, like it is on the select screen.
* Can the Name field become bigger if it is selected, enough to show the whole name?
* Can the dice button be moved so that it can't be as easily accidently hit?
* Should the dice button warn if there is text in the name that is modified from random state?
* Is there a need for a genera "cancel" that reverts any changes made to the seed metadata just made?

**Comment by ChristopherA** [comment]
This was particularly problematic in one case. I was editing it and I don't remember what the original name was, and there was no description, so I've had to name it as Unknown. It could be one of my lesser test seeds or from an oddball third-party wallet, but it also might be one with real UTXOs on it. I went to seedtool on my other device, and the name change propagated in iCloud, so I have no idea what this seed is.

I'm elevating this to bug.

**Comment by wolfmcnally** [comment]
This should be addressed in tonight's beta.

**Comment by shannona** [comment]
The "..." icon that pops up the dice and clear buttons now disappears when you're editing.

However,
* There is no "undo".
* There is no general "cancel".
* There is no protection against hitting dice or clear if there is text in the name that's been changed.

It looks to me like the core problem is likely resolved, but not additional requests @ChristopherA had.

@ChristopherA, is this sufficient to close, possibly adding additional tasks onto long-term lists?

**Comment by shannona** [comment]
Remaining issues flagged in #172.
