### ISSUE TITLE
Allow printing of individual SSKR shares

### ISSUE THREAD

**Issue by wolfmcnally** [BlockchainCommons/GordianSeedTool-iOS#166]
SeedTool allows individual shares to be individually exported as URs, or as ByteWords, or as QR codes, or written to an NFC tag. Currently it only allows printing all shares to either aggregated coupon pages, or one page per share in the same print job.

The purpose of this enhancement is to add the ability to export individual shares to separate print jobs, which will allow them to be printed, or individually exported as PDFs by the share sheet, which would allow sharing individual shares with other people via AirDrop or saving them to the file system.

This additional functionality would be added to the same UI that allows the other forms of individual share export.

Non-goals of this enhancement include:

* Adding a separate "export to PDF function," instead relying on the existing PDF export function of the printing API.
* Exporting *all* shares to separate PDFs in a single operation.

**Comment by wolfmcnally** [comment]
This is a simplification/step towards the ideas discussed in #123 .

**Comment by wolfmcnally** [comment]
Ready for test in 1.5 (59).

**Comment by shannona** [comment]
UI all looks good. Individual entries pull up correct shares. Printing works. Looks good.
