### ISSUE TITLE
Allow Export of crypto-hdkey to NFC cards

### ISSUE THREAD

**Issue by wolfmcnally** [BlockchainCommons/GordianSeedTool-iOS#167]
Currently SeedTool provides for the export of writing `crypto-seed` and `crypto-sskr` to NFC cards. It also provides for reading these two formats.

This enhancement would provide for the writing of `crypto-hdkey` to NFC cards.

This functionality would appear in the UI in the same places that let you export `crypto-hdkey` other ways.

Non-goals for this enhancement include:

* Reading `crypto-hdkey`, as no other aspect of SeedTool currently allows for reading `crypto-hdkey` in other formats.

(refactored from #124)

**Comment by wolfmcnally** [comment]
Ready for test in 1.5 (59).

**Comment by shannona** [comment]
Successfully wrote an hdkey with GST.

Successfully read it with NFC Tools.

Looks good.
