### ISSUE TITLE
NFC: Allow reading of crypto-request and and writing of crypto-response

### ISSUE THREAD

**Issue by wolfmcnally** [BlockchainCommons/GordianSeedTool-iOS#168]
SeedTool currently uses the camera or the clipboard to read `crypto-request` objects, and uses the camera or clipboard to export `crypto-response` objects. We would also like to be able to use NFC cards for this purpose.

This enhancement will provide for SeedTool reading and processing `crypto-request` from NFC cards, and provide for writing `crypto-response` to NFC cards.

Reading and writing may be done from diverse formats. For example a `crypto-request` may be read from a QR code, and then the `crypto-response` written to an NFC card.

(refactored from #124)

**Comment by shannona** [comment]
Able to write a crypto-request, read the crypto-request, approve a response, write the crypto-response, and then test that crypto-response in NFT Tool
