### ISSUE TITLE
QR code shown for signature request too small to read from phone. Make it full screen?

### ISSUE THREAD

**Issue by drewballs** [BlockchainCommons/GordianSeedTool-iOS#177]
UR:CRYPTO-PSBT QR code generated to sign for transaction. Would it be possible to have this expand to fill the whole screen of the phone as I can't get the wallet to read the QR code as it's too small. It works on the iPad. Thanks

**Comment by shannona** [comment]
This should be resolved in the newest Testflight version.

The size of the QR hasn't changed, but the tight static QR has been replaced with a less compact animated QR. I've tested it out with Sparrow where I couldn't read the static QR in recent versions, and the animated works fine.

So, closing this, though we still need to do a release of that Testflight to get this update out!
