### ISSUE TITLE
Reduce animated QR code threshold

### ISSUE THREAD

**Issue by wolfmcnally** [BlockchainCommons/GordianSeedTool-iOS#184]
A PSBT QR code too dense to read easily on some devices. Next build of SeedTool should reduce the animation threshold further.

**Comment by shannona** [comment]
Here's what we're currently seeing:

![IMG_5619 (1)](https://user-images.githubusercontent.com/1110886/231252061-f2d5b84c-d47b-4ebc-ae6a-7f4c1a7600cb.jpeg)

**Comment by wolfmcnally** [comment]
Should be fixed in build 64 (forthcoming.)

**Comment by shannona** [comment]
Tested. That same simple PSBT now generates an animated psbt. And the more readable PSBT now scans quickly back into Sparrow. So success all around. Thanks!
