### ISSUE TITLE
UX Bug: BIP39 word entry

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianSeedTool-iOS#186]
There is a difference between reporting an invalid bip39 word vs the checksum being invalid. User was legitimately confused thinking the world was invalid. 

![IMG_1640](https://github.com/BlockchainCommons/GordianSeedTool-iOS/assets/69103/3b9430e1-2e8a-4f47-9782-7622f8960102)

Error shown be more granular: incorrect word, insufficient quantity of words, checksum invalid.

**Comment by ChristopherA** [comment]
We should make a bigger test case for BIP39 seeds. Extra spaces,  extra at end or beginning, comma, comma space (or not), CR or CR/LF  between. Both full word and 4 characters words. We should make it as easy as possible to bring in old seeds.

**Comment by shannona** [comment]
Comma separated, space separated, tab separated, and return separated all work in GST 1.6.

I think the major UI issue here is that GST will report "Invalid BIP39 words." as you're typing them in, up to the point where you have a complete, valid set added.

**Comment by wolfmcnally** [comment]
Please retest in next release.

**Comment by shannona** [comment]
I'm still seeing errors as you type words in, @wolfmcnally , both in the 4-letter form and complete form, only clearing when the last letter of the last word is typed.

![IMG_6209](https://github.com/BlockchainCommons/GordianSeedTool-iOS/assets/1110886/d989fef0-9edd-444a-b99d-632e656d083b)

**Comment by shannona** [comment]
Minor suggestion on "No valid SSKR shares found" error message. We should add the word: "yet", ie, "No valid SSKR shares found yet".

![2FF46B5C-638E-430E-9C82-91ACA852D3F1](https://github.com/BlockchainCommons/GordianSeedTool-iOS/assets/1110886/ee1c1880-d789-4ae8-a813-4834dcb4c09d)

**Comment by shannona** [comment]
A bigger issue: when an error appears, it sticks around. So after I accidentally mistyped "fly" and "fky", I got an "Invalid BIP39 words" message, but it didn't go away when my iPhone helpfully corrected that word.

![DD1583CD-AEC3-4544-840B-B25B9B875D25](https://github.com/BlockchainCommons/GordianSeedTool-iOS/assets/1110886/012195a4-1164-4d4a-ba2a-ee6c015062a0)

**Comment by shannona** [comment]
This still shows "Invalid BIP39 words." as you're typing in correct BIP39 words.

**Comment by shannona** [comment]
The new red/green/yellow words at bottom are amazing and should be a great UI for entering words. I think we still need to change the error message though.

I suggest "Invalid BIP39 words" only if something comes up red.
Otherwise, maybe "BIP39 word import not complete" or "BIP39 words incomplete".
