### ISSUE TITLE
Simple Yimn Blue Doesn't Scan

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianSeedTool-iOS#188]
The simple Yimn Blue seed with no additional data doesn't scan in GST 1.6 (67):

![](https://raw.githubusercontent.com/BlockchainCommons/crypto-commons/master/images/vectors/vector-seed-yinmn.png)

Now does our Yimn Blue with date:

![](https://raw.githubusercontent.com/BlockchainCommons/crypto-commons/master/images/vectors/vector-seed-yinmn-date.png)

(The error is "Unrecognized format")

The rest of our [test vectors](https://github.com/BlockchainCommons/crypto-commons/blob/master/Docs/crypto-seed-test-vectors.md) do, including variations of Yimn Blue that add more info and our 256-bit test vector, even the versions with no data and just date.

**Comment by wolfmcnally** [comment]
I'm not sure where you go that first QR code. It contains:

```
ur:crypto-seed:/A1015059F2293A5BCE7D4DE59E71B4207AC5D2
```

Which is not a well-formed UR. As you mentioned, the second QR code reads fine.

**Comment by shannona** [comment]
Verified the problem was the test vector (sigh). Fixed the test vector. Retested. Verified as OK.
