### ISSUE TITLE
Crash with Camera

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianSeedTool-iOS#189]
* Opened my camera
* Pointed at QR
* Watched the "Open in SeedTool" text appear
* Clicked on the "Open in SeedTool" text
* Watched the seed open in SeedTool
* Heard the chime
* Watched SeedTool crash

This has not (yet) been replicable, but I sent a crash report on the first one, which will hopefully get to you and illuminate what was going on.

**Comment by wolfmcnally** [comment]
I found the crash report, but unfortunately it was unhelpful— the stack trace doesn't pass through any of my code. Googling for similar problems shows other developers reporting somewhat similar crashes over the past several years, but nothing seemed relevant to our situation. Obviously I wan't about to replicate the error myself. I think the best we can do is collect any future crash reports and see whether they form a pattern.

**Comment by shannona** [comment]
This has proven non-replicable for me either.

**Comment by shannona** [comment]
It sounds like it's likely upstream if it doesn't pass through any GST code, but I guess leave it open while we see if it shows up again with any more crash reports?

**Comment by wolfmcnally** [comment]
Sure.

**Comment by shannona** [comment]
Closing this out as I'm doing new testing today and it's not coming up.
