### ISSUE TITLE
Paste doesn't Work in Hex Entry

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianSeedTool-iOS#190]
Under + (add Seed) / Hex Bytes, text can't be pasted.

It can't be pasted by holding and popping up a menu, but also not by choosing "Paste" off of the "..." menu.

**Comment by wolfmcnally** [comment]
I was not able to replicate this. I produced a hex seed using the command line `seedtool` on my Mac, copied it, then used the networked pasteboard to paste it into the Hex input field. Note that this is *not* a regular text field, so it has no insertion point: you have to either enter the hex using the hex keypad, or paste it into the field using the Paste command in the `...` popup.

**Comment by shannona** [comment]
I had previously been unable to get the ...Paste feature to work, but today it does, so we'll call this non-replicable and close. Thanks.
