### ISSUE TITLE
Classic ur:crypto-request for Seed or Key fails

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianSeedTool-iOS#192]
These are my test vectors:
https://github.com/BlockchainCommons/crypto-commons/blob/master/Docs/crypto-request-test-vectors.md

They all failed with `unrecognized ur:crypto-request`

**Comment by shannona** [comment]
Animated QR requests for PSBT signing still seem to work fine, so this issue is restricted to requests for keys and seeds

**Comment by wolfmcnally** [comment]
This is correct. We are replacing all `ur:crypto-request`  and `ur:crypto-response` with envelope-based requests and responses.

**Comment by shannona** [comment]
I've marked our `crypto-request` test vectors as deprecated. We should probably consider writing some new Envelope test vectors, @ChristopherA .

**Comment by wolfmcnally** [comment]
Yes, and we should deprecate our BCRs with the olde definitions in them and/or update them with the envelope-based definitions.
