### ISSUE TITLE
No Way to Response to a ur:crypto-request for a PSBT Signature

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianSeedTool-iOS#195]
The workflow for a PSBT signature that comes in by a ur:crypto-request is now:

1) Receive `ur:crypto-request`.
2) Look over info
3) Sign
4) Authenticate
5) Send back a response as `ur:envelope`

This doesn't work with people already using `ur:crypto-request`, and not recognizing `ur:envelope`, such as Sparrow.

Obviously, we still need a `ur:crypto-response` option for sending back a signed PSBT, but IMO it should be the default if something came in as `ur:crypto-request`.

**Comment by wolfmcnally** [comment]
We still sign bare PSBTs. In my last conversation on this with @ChristopherA on this we agreed we were dropping all `ur:crypto-request` and `ur:crypto-response` in favor of envelope-based requests and responses as no one is actually using requests or responses yet. We are deprecating the older style requests and responses.

**Comment by shannona** [comment]
There's a problem with interaction with Sparrow, but it turns out to be one generation back: `ur:crypto-psbt` instead of `ur:crypto-request`. So no-one-is-using-it seems a fine response to this, and I'll file the other separately.
