### ISSUE TITLE
Print is Wrong Color Under SSKr

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianSeedTool-iOS#196]
Under the SSKR Export, all the options are yellow until you hit "Print All Shares", then the next "Print" button is green.

**Comment by wolfmcnally** [comment]
This is as expected. The `Print` button has app accent color: green. This is just like all the other normal buttons like `Done` and `Cancel`. The distinction between green and yellow in buttons is made when the button exports potentially sensitive information. In the case of the `Print` button when printing a seed or SSKR share, the user has already passed that decision point here:

![image](https://github.com/BlockchainCommons/GordianSeedTool-iOS/assets/676176/646094a5-5c68-4f4f-ae6b-aba1d57a18c2)

Once the user gets to the print preview page, the actual button to print is just the app accent color:

![image](https://github.com/BlockchainCommons/GordianSeedTool-iOS/assets/676176/f0fe14f4-b816-4e70-bfd0-0c779917a992)

**Comment by shannona** [comment]
I personally think it's an inconsistency, but see your viewpoint.
