### ISSUE TITLE
NFC Write: Tag Not Connected

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianSeedTool-iOS#197]
Trying to Write SSKR Shares to NFC Tags fairly reliably gives the error "Tag Not Connected". I tried it on what I believe was a fresh NFC and one that already had a crypto-hdkey on it.

**Comment by wolfmcnally** [comment]
I have replicated this and verified the problem is *not* in Apple's sample code. So I am investigating.

**Comment by wolfmcnally** [comment]
Fixed.

**Comment by shannona** [comment]
Tested read & write. All OK.
