### ISSUE TITLE
Print Error for Gordian Envelope

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianSeedTool-iOS#200]
Choosing Authenticate -> Share -> Gordian Envelope and then the Print option (Print with HP Smart in my case) generates the error "File Type Not Supported"

![646EBEFC-194C-456E-9DCB-3467115FED12_1_102_o](https://github.com/BlockchainCommons/GordianSeedTool-iOS/assets/1110886/b2cd2edd-d8b0-4268-89f3-1e94fc14585f)

Everything else from that menu (Bytewords, BIP 39 Words, Hex) seems to print fine.

**Comment by shannona** [comment]
This is still the case. I can print Gordian Envelope fine from the Backup->Gordian Envelope pages.

Not entirely sure why there's this duplicate option.

**Comment by shannona** [comment]
Still generates an error.

**Comment by wolfmcnally** [comment]
I don't seem to be able to replicate this. Per your instructions, I go to Authenticate -> Share -> Gordian Envelope:

![IMG_8599](https://github.com/BlockchainCommons/GordianSeedTool-iOS/assets/676176/61576243-00b5-4b2b-a409-56e4b2980edd)

And this is the screen I am presented with. There is no print option available:

![IMG_8600](https://github.com/BlockchainCommons/GordianSeedTool-iOS/assets/676176/ce0fc511-6380-4bbc-bfc1-9483616ef24b)

So I'm confused. If you go to Authenticate -> Backup -> Backup as Gordian Envelope there is a Print option:

![image](https://github.com/BlockchainCommons/GordianSeedTool-iOS/assets/676176/86aeb881-05f2-4001-8ee3-774e3139c915)

When selected I get the print preview as expected:

![image](https://github.com/BlockchainCommons/GordianSeedTool-iOS/assets/676176/ca3f750c-d34f-4cfa-901c-685905b10126)

And I am able to select my physical printer or any of the virtual printers in Apple's developer Printer Simulator:

![image](https://github.com/BlockchainCommons/GordianSeedTool-iOS/assets/676176/933cadd4-b1d8-4ec9-abeb-c685ab1f3db4)

**Comment by shannona** [comment]
It's a share sheet option, maybe? So, it sounds like what's broken might be
outside your control.

I wonder if there's any way to disable that option so that you maintain
control over whether printing is available or not?

[image: IMG_8107.png]

Shannon

**Comment by shannona** [comment]
Closing this, as it seems an external/HP option that only shows up on my phone.
