### ISSUE TITLE
Request/Response Not Consistent for Ethereum & Tezos

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianSeedTool-iOS#204]
Two issues here that may or may not be the same.

1.) The Ethereum & Tezos keys are inconsistent as to whether they have the request/response developer buttons available. To be precise: the HD keys have them, the non-HD private keys don't (but also see my notes on #203).

2.) The requests that do exist, for the HD keys, don't work. For example the following request can be generated to request the private HD Key for Ethereum for our 128-bit seed:
```
ur:envelope/lstpcstansfytansgshdcxdihfiyhhwnvegswkheihsazmrfmeaottvloxtyleythszmhfhththkrpgavstpbyoycsielstpcstansfgcsihoytpcstansflcssotpcstantjootadlecsdwykcsfnykaeykaewkaewkaocyhngrmuwzaxahoytpcstansflcssblfcfaddmoycfadmhcfadmeoyaatpcskspsgljljkjyjpkpjncxiykpioinhsjycxjpihiniainihjtieinjkcxjpihjpkpjncxkoihjzinjycxjzhskpiehsjtjyinkpjncxkojljzkpjojyhsjyihcxkoihjtinhsjncxihjzinioihjtieincxkoihjzinjycxjzhsidjljpihcxiajljpjpkpjojyincxjskpinhscxieihjzihiajykpjkcxkojljzkpjojyhsjkcxjpihjndmcxfejkjycxihjycxihksjojziniahsidjlcxjoihjpiyihjpihjtieinjkcxjpihjoihjzjzihjtiekpjkcxhsjzinhsjkdmfsrleydr
```
When fed back into GST, the response is "Unknown request type"

**Comment by shannona** [comment]
(These might be the same issue if the answer is "None of those should have response/request, but otherwise if you want me to create a new issue for any of this, let me know.)

**Comment by wolfmcnally** [comment]
This issue is now mooted by the fact that in the next release HD Keys are no longer shown for Ethereum or Tezos.

**Comment by shannona** [comment]
HD Keys indeed gone, so closing.
