### ISSUE TITLE
Signature Requests Muddle Text Together Due to Master Fingerprint

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianSeedTool-iOS#207]
The addition of the Master Fingerprint has caused a few lines of text on the signature requests to partially overprint.

![89C64DCB-EE09-48C6-9C02-EBB8CCBEE377_1_105_c](https://github.com/BlockchainCommons/GordianSeedTool-iOS/assets/1110886/502032ab-515c-4769-95b6-911156600f33)

**Comment by wolfmcnally** [comment]
Fixed in next release.

**Comment by shannona** [comment]
![8E528F2D-6698-4E24-93C7-0CBD39B51DDC_1_102_o](https://github.com/BlockchainCommons/GordianSeedTool-iOS/assets/1110886/6ef28d94-bf20-4f7b-8f74-11e1c19049f7)
 
(Looks good.)
