### ISSUE TITLE
First Time Paste From Other Device Fails (Hex)

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianSeedTool-iOS#209]
Sometimes the first time I paste from another device I get a privacy query:

![0F21E98A-971B-4AE8-9395-F2A235877CD3_1_102_o](https://github.com/BlockchainCommons/GordianSeedTool-iOS/assets/1110886/bb24f06f-140a-4bef-b581-e11ce9946008)

When that happens, after I select "Allow", the paste fails. It _might_ paste it in then erase it, because it looks like the paste appears for a second before disappearing.

This problem has only been identified on Hex Bytes, and it's not exactly clear when the iPhone requires a privacy query. I was able to get it three times in a row by restarting GST, and then it stopped appearing afterward.

**Comment by wolfmcnally** [comment]
Note that the privacy query can be turned off in Settings -> Seed Tool -> Paste From Other Apps -> Allow.

But this doesn't solve the error, just gets rid of the authorization alert.

**Comment by wolfmcnally** [comment]
Could not replicate under iOS 17.3, may have been an iOS bug, so please retest.

**Comment by shannona** [comment]
Fixed.
