### ISSUE TITLE
UX: hint which network is default here.

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianSeedTool-iOS#48]
Minor, but since you can’t tell purely on this screen if you are default on testnet or mainnet, can you put the appropriate net icon here so you can know which kind of xpub it will be? I know you can see it on next screen.
![PNG image](https://user-images.githubusercontent.com/69103/118312968-061c7b00-b4a7-11eb-83b0-fa0d6e796861.png)

**Comment by wolfmcnally** [comment]
Actually it puts the TestNet icon there if it's going to be on TestNet, and omits it otherwise. Do you want to show it in both cases?

![image](https://user-images.githubusercontent.com/676176/123353587-adfd7d80-d516-11eb-8c84-f7228aa12456.png)

**Comment by ChristopherA** [comment]
Yes.
