### ISSUE TITLE
New Text for SeedTool

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianSeedTool-iOS#52]
_I'd like to raise the prominence of the "About" page for the app, which is currently buried at the bottom of the "I" menu. My suggestion would be to move it to a pop-up from the icon for SeedTool at the top-middle of the menu, which will match how QRTool does it. It's that's too burdensome, at the least we should move it to the top of the "i" menu and change its name to "About Gordian Seedtool"._

Here's totally rewritten text. 

> Gordian Seedtool is open-source software that is a project of Blockchain Commons. It was created to allow the offline creation and storage of seeds for use primarily with cryptocurrencies. It allows you to create robust seeds by a variety of means (or to import seeds from other sources), to store those seeds in a secure manner, and to easily export your seeds or their key derivations when you're ready to use them. Note that it is not a Wallet, simply an accessory to support your safe use of other Cryptocurrency applications

> Gordian Seedtool demonstrates the Gordian principles. It allows you maintain control of your own key material (independence), stores them on your closely held mobile device (privacy), protects them with 2FA and biometrics (resilience), and communicates via QRs and URs (openness).

> Creating reference applications of this sort supports the goals of Blockchain Commons, to enable responsible key management and to support self-sovereign solutions. Blockchain Commons is a "not-for-profit" social benefit corp committed to open source and open development.

> [Visit Our Support] -> https://github.com/BlockchainCommons/Gordian/discussions

> [Visit the Repo ] -> https://github.com/BlockchainCommons/GordianSeedTool-iOS

> [Visit Our Website] -> https://www.blockchaincommons.com/

**Comment by shannona** [comment]
I'd also suggest the following new text for the store, using some new, more sales-oriented organization that I'm trying out:

==
STORE YOUR CRYPTOGRAPHIC SEEDS SAFELY!

“Seeds” are long strings of truly random numbers used in cryptocurrencies. As the name suggests, they're the starting point for other things like private keys, public keys, and payment addresses. To keep your funds secure, seeds need to be generated and stored safely. Gordian Seedtool lets you generate those seeds and store them securely in your device's keychain. You can even use an entirely offline device (without Internet access) to guard your seeds, and use QR codes to exchange just the necessary information with online devices that are running compatible wallet or signing software.

Features:

- Cryptocurrency Focus
Gordian Seedtool includes easy functionality for deriving signing and verification keys for either Bitcoin or Ethereum.

-Encrypted Protection
Your keys are fully encrypted.

- Biometric Support
Decrypting your keys requires use of your biometrics, such as a Touch ID, to ensure no one but you can see them.

- Integrated Backup
Gordian Seedtool allows the backup of your seeds using sophisticated methods, including printed pages and Sharded Secret Key Reconstruction (SSKR), which lets you split your seed into pieces and send them to trusted parties, who can send them back to you in an emergency, allowing you to recover your seed.

- Private Data
Your data is never shared with any third parties; only your device can access and decrypt your seeds.

- Standardized Interoperability
Gordian Seedtool uses the QR and UR specifications to make it easy to import and export seeds and keys.

To read more about the app check out the repo at: https://github.com/BlockchainCommons/GordianSeedTool-iOS

To read more about Uniform Resource check out the repo at: https://github.com/BlockchainCommons/Research

To read more about Blockchain Commons visit our website: https://www.blockchaincommons.com

**Comment by shannona** [comment]
I added a link for support, as we've now got Discussions for Bugs, Features, Q&A. It could be this should be more prominent:

> [Visit Our Support] -> https://github.com/BlockchainCommons/Gordian/discussions

**Comment by wolfmcnally** [comment]
@shannona I've updated the text in the app with your app and moved it to the top.
@ChristopherA I'll get the new store text in the next release.
