### ISSUE TITLE
Version 1.0 (20) crashes on startup with Test flight on iOS 14.6

### ISSUE THREAD

**Issue by henkvancann** [BlockchainCommons/GordianSeedTool-iOS#53]
is this a known issue? It says 'expires in 77 days'
 The only thing I did was pushing the 'Open' button.

**Comment by wolfmcnally** [comment]
Please try deleting and reinstalling the app. I think this only affects Test Flight users up to the version where we added iCloud syncing.

**Comment by henkvancann** [comment]
Was solved with version 1.0.1, thanks.
