### ISSUE TITLE
Not able to edit seeds added in QR Tool on MacBook Air M1.

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianSeedTool-iOS#54]
I have downloaded release version of SeedTool from App Store (1.0) and I can use QR to add a seed (in this case the demo #SmartCustody seed), but I couldn't edit name before I saved, and when I tap on seed in list, nothing happens.

**Comment by wolfmcnally** [comment]
@ChristopherA Is this still happening with the latest release of QR Tool and Seed Tool?
