### ISSUE TITLE
Mac iCloud Sync failing

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianSeedTool-iOS#55]
The seed I added on release SeedTool Mac (which I can’t edit there due to #54) did successfully arrive on my release SeedTool on iPhone when after I downloaded it and launched it.

However, the changes I made to it on iPhone (renaming it, date, notes) have not propogated back to Mac. It is the same as it was before.

Note, that the Mac app crashed while idle but I wasn’t able to send crash crash report — may be related (maybe it crashed when I edited on iPhone and it attempted to sync back).

**Comment by wolfmcnally** [comment]
Please check the 1.0.1 release. This should have improved significantly.

**Comment by shannona** [comment]
From what I've seen of recent usage, it's now syncing correctly.
