### ISSUE TITLE
Key Labels Changed

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianSeedTool-iOS#56]
![PNG image](https://user-images.githubusercontent.com/69103/124065886-7f871300-d9ec-11eb-829f-e080bac1b70c.png)

 I’ve decided due to some likely changes to how multisig 48 derivations are being done on other wallets, and how some new better ideas are emerging, we should not use the word Gordian here. 
 
For now the first is just a Cosigner Public Key, the second is a Cosigner Private Key.

**Comment by wolfmcnally** [comment]
This will be fixed in 1.0.1.
