### ISSUE TITLE
Bug: Mac QR Camera 90° Counterclockwise

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianSeedTool-iOS#58]
In release version 1.0 on M1 MacBook Air on Big Sur 11.4, the QR button dialogue leads to a camera with wrong orientation.

**Comment by wolfmcnally** [comment]
I was unable to replicate this on my Mac. Please see whether there is any difference in the 1.0.1 release.

**Comment by ChristopherA** [comment]
Confirmed fixed in GST version 1.3.3 (51). Closed.
