### ISSUE TITLE
Import SSKR Cancel Does Not Work After Invalid SSKR Shares

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianSeedTool-iOS#61]
After inputing an invalid SSKR share, I could no longer cancel. It just blinks light and then goes dark again.

Testflight 1.0.1 (21), iPhone8

**Comment by shannona** [comment]
(I've had no luck replicating this, but I was very much stuck after pasting in one set of words, getting that message, and pasting in the second set, and still getting it, and after that I couldn't cancel.)

**Comment by wolfmcnally** [comment]
I was unable to replicate this issue. Please let me know if you see it again.

**Comment by shannona** [comment]
Closing unless it shows up again. (I tried to replicate it precisely without luck.)
