### ISSUE TITLE
"Invalid SSKR Shares" Message Incorrect for Insufficient Shares

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianSeedTool-iOS#62]
When pasting in SSKR words or `ur:crypto-sskr` shares via the , GordianSeedTool gives the message "invalid SSKR shares." if you post correct shares, but ones insufficient to reach the threshold. This message is not accurate.

Since this may be a common methodology, with someone pasting in shares from multiple places, we could do with better messaging here, such as "X shares input; Y more needed to meet threshold and reconstruct seed".

Or, for a more complex setup: "X shares input; Y groups still have not met their threshold. Input additional shares to reconstruct seed."

**Comment by wolfmcnally** [comment]
By definition, insufficient shares to reconstruct a seed are invalid for that purpose, so the message is terse but not inaccurate. I have enhanced the message to read "Invalid or insufficient SSKR shares." If you would still like more detailed feedback messages, please open a new enhancement issue.
