### ISSUE TITLE
SSKR Shares Erase Themselves When Cut and Paste

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianSeedTool-iOS#63]
Sometimes when you're cutting and pasting into the Import SSKR page, the old paste suddenly erases itself before you get to the new one. I can't tell the rhyme or reason here, but it seems to happen about one time in three.

**Comment by wolfmcnally** [comment]
Can you please send me a screen recording of this happening?

**Comment by shannona** [comment]
I can no longer replicate it, so we'll file it away until it appears again (if it does).
