### ISSUE TITLE
Valid seed-oriented QRs Seed Tool doesn’t read

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianSeedTool-iOS#66]
![IMG_4327](https://user-images.githubusercontent.com/69103/124845125-e9eb0680-df4a-11eb-8e4b-8248f15ccbd7.jpeg)

**Comment by ChristopherA** [comment]
I’m not sure what is wrong with the seed QR on this page. In any case, should give a better error “12 words but invalid mnemonics” or “insufficient words” http://boonpets.com/cryptomarket-help/bear-bitcoins-bitcoin-wallet-qr-code-generator/

**Comment by ChristopherA** [comment]
Here is another one that is invalid.

https://github.com/spesmilo/electrum/issues/3663
 
Maybe both of those are elecrtrum mnemonics? We may want to support inputting those someday, but in the meantime maybe if we recognize it is a wrong mnemonic set tell people “Electrum mnemonics are not supported.

**Comment by ChristopherA** [comment]
Maybe with invalid show what you did get or button to a debugging dialogue so you can see & copy text?

**Comment by ChristopherA** [comment]
Page 17 of https://www.criptoro.com/wp-content/uploads/2020/12/CRIPTORO_WALLET_USER_GUIDE.pdf

**Comment by ChristopherA** [comment]
This 24 word mnemonic should work: 
<img width="768" alt="PNG image" src="https://user-images.githubusercontent.com/69103/124847954-c460fb80-df50-11eb-8747-1bdb96b6d2c5.png">

**Comment by wolfmcnally** [comment]
The raw text in that QR code is:

```
1. elevator
2. prepare
3. flat
4. craft
5. scene
6. song
7. theme
8. bacon
9. security
10. odor
11. fortune
12. celery
```

Seed tool currently only supports reading URs. This is a design choice and I recommend we stick with it. There is no spec for a "BIP 39" QR code that I am aware of, so how do we support this? How do we identify this as BIP39 and not some other encoding? What do we do with the line numbers? What if they're wrong? What if they're bullets instead?

**Comment by ChristopherA** [comment]
I do think we should consider raw word QRs. At least until more wallets support ur-cryptoseed. 

It turns out Electrum has been doing QRs for seeds for some time (both it’s own original pre-bip-39 words and current bip39) thus I think people will expect it. Google image search shows lots of these from Electrum as many people wrote suggesting printing them. 
 
FullyNoded & Gordian Wallet have always offered export of seeds words via QR. clearly few use GW, but I don’t know how many people use FN (a least hundreds given telegram channel).  The numbered example was from GW.

I need to go through more existing wallets to see what they are doing. 

But I do concede that this doesn’t need to be a 1.0.2 feature.

**Comment by ChristopherA** [comment]
Postal’s Law & common IETF motto: “  "be conservative in what you do, be liberal in what you accept from others"

thus we don’t need to export non-UR seeds, but we likely want to make them more easy to add.

**Comment by wolfmcnally** [comment]
I agree with the adage. And also the adage, "Be open-minded, but not so open-minded that your brain falls out." The question I asked above demand answers: What _exactly_ is the format we're supporting here? BIP39 with line numbers? Where is it documented? You show me a spec, and I'll support it.

**Comment by shannona** [comment]
I've added an Investigation folder to the Research Repo, and documented these there:
https://github.com/BlockchainCommons/Research/blob/master/Investigation/Formats.md
