### ISSUE TITLE
Future seed format to consider supporting 

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianSeedTool-iOS#67]
The QRs on #66 we should support. 

These we may want to consider converting in future:

**Comment by ChristopherA** [comment]
An encrypted seed:
https://anderson-arlen.github.io/cryptoseed/

**Comment by wolfmcnally** [comment]
Personally, I'd want to see significant adoption of this before we endorse it and go through the trouble of supporting it in all our work.

**Comment by ChristopherA** [comment]
Related is how ColdCard and Foundation Devices Passport have encrypted seed files, as per https://github.com/BlockchainCommons/GordianSeedTool-iOS/issues/138

cc/ @FoundationKen @zachherbert

**Comment by shannona** [comment]
I've added an "Investigation" folder to our Research Repo, and documented all of these possibilities there:
https://github.com/BlockchainCommons/Research/blob/master/Investigation/Formats.md
