### ISSUE TITLE
Different Export Functionality for Key Derivation

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianSeedTool-iOS#68]
The "Derive and Export Key" option allows exporting by copying base58 while the "Cosigner Private Key" button does not.

**Comment by wolfmcnally** [comment]
The "Derive and Export Key" function is considered the "full" version of the key derivation feature, while the "Cosigner Public Key" and "Cosigner Private Key" are considered shortcuts for the workflow we'd *like* people to use. As such, it doesn't include every possible export format.

**Comment by shannona** [comment]
I think this is even more important now that the pages look identical, except the Cosigner Private/Public Key pages are missing that extra "Base58" button (and the developer options).

**Comment by wolfmcnally** [comment]
@shannona Please review and revise this issue if necessary.

**Comment by ChristopherA** [comment]
@shannona can you re-review this for 1.4?

**Comment by shannona** [comment]
Verified this is still an issue, and reIssued it as #148.
