### ISSUE TITLE
FEATURE: Choose default derivation and export for public/private in Settings

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianSeedTool-iOS#70]
Right now the default export is UR for the Cosigner derivation in the public key and the encrypted private key. I'd like to see in settings that you have some more default choices:

* Bitcoin Master via UR
* Bitcoin Master via fingerprint+path+xpub/xprv
* Ethereum Master via UR
* Ethereum Master via fingerprint+path+xpub/xprv
* Bitcoin Segwit Single Key via UR
* Bitcoin Segwit Single Key via fingerprint+path+xpub/xprv Segwit (note that this may in zpub form in a piss-poor convention)
* In near future we need to support Taproot Single Key form https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2021-June/019096.html
* Custom, which asks for name to put as label for this default, and a path in either 1h or 1' form, and if it is in the list at https://github.com/satoshilabs/slips/blob/master/slip-0132.md use the appropriate ?pub ?prv form, otherwise xpub/xprv.

I don't want to support legacy, nested segwit or any of the other forms in the defaults list. If they are using some weird derivation for an oddball wallet, another blockchain, etc., then they must to use custom.

**Comment by ChristopherA** [comment]
We should also make sure that all these default forms above are available in the regular export derived keys options.

Possibly another default choice is empty for xpub and go immediately to sskr export page for decrypt.

**Comment by wolfmcnally** [comment]
For each of the pairs where you've specified "UR" *and* "fingerprint+path+xpub/xprv", I think these should probably be a single choice that allows you to take the form of output you want. For example, if you derive a Bitcoin Master, we show *both* the UR as we do now, and also allow copying of the "fingerprint+path+xpub/xprv" from the same output screen.

**Comment by wolfmcnally** [comment]
I have added support for Segwit and custom derivation paths for Seed Tool 3.2. It looks like the Taproot Single Key spec has not finalized the Purpose value yet. Please open another ticket for that when it's ready.
