### ISSUE TITLE
FEATURE: sskr scenarios selector

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianSeedTool-iOS#71]
At the top sskr selections, a choice of some common scenarios, and an internal link to explain them your help markdown. When selected, the group and keys choices below are changed.

* 1:1 — alternative to BIP39, easier to memorize and readable over the phone.
* 2:3 — typically for three locations
* 3:5 — either 5 locations or 2 locations and 3 family/friends/associates
* 4:9 — for larger number of family/friends/associates
* Two of Three 2:3 — special version of 4:9 (and only in this list) two-layer scenario. Typically 4 of the sskrs from two groups are in four different locations, the rest are distributed socially between two disparate groups (typically family and non-family). Thus you can self-sovereign restore from the locations, and if all locations are lost you can socially recover with 4 of the 5 social ones, and of course there is tween where if one location is bad you can recover socially.

**Comment by shannona** [comment]
This is available by version 26.
