### ISSUE TITLE
UX: Burying the Lede on Export Features

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianSeedTool-iOS#72]
So far, no one that I’ve talked is finding the share button under Decrypt, or even knows to look for features there. This is 3 for 3. All are puzzled. 

![PNG image](https://user-images.githubusercontent.com/69103/125725785-c3dbbb63-a888-44af-859f-fead8936ecb7.png)

We need to find another way for people to discover how to export, or how to use these features for some common tasks, in particular ur:crypto-seed and ur:crypto-sskr. 

I’m not necessarily saying we remove this share button, as there are a number of options there I don’t want to promote but we need for legacy. But we need some alternative ways that more easily discovered for the scenarios we want to encourage the most.

**Comment by ChristopherA** [comment]
I’m the short term in 1.1.1 or 1.2 maybe we just add to the UI label “Data” the text “and Export”.

**Comment by wolfmcnally** [comment]
I think the thing to do is put some explanatory text near the "Decrypt" button that says, "Decrypt the seed to export it or derive keys from it."

**Comment by shannona** [comment]
This has been dramatically redesigned by version 26, so that there are now obvious Backup, Share, and Derive Key buttons.
