### ISSUE TITLE
Suggested Changes for Key Derivation Functions

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianSeedTool-iOS#74]
We should change the "Other Key Derivations" to "Standard Key Derivations" to show that it's a few, select derivations that we've chosen.

This then opens the path for a true "Other Key Derivations" which would allow a user to export a key derivation with a `ur: crypto-request` demanding it. An easy first-draft of this would be to allow someone to just paste in the fingerprint + derivation path. We can reject it if the format isn't right, otherwise create the requested key.

**Comment by wolfmcnally** [comment]
@shannona Given the recent changes to how I'm doing key derivation, what changes would you make to this issue?

**Comment by ChristopherA** [comment]
@shannona Is this resolved with 1.4?

**Comment by shannona** [comment]
Yes. With the "Custom" stuff there, this really is "Other Key Derivations".
