### ISSUE TITLE
PRIORITY: Derive Root Ethereum Account Address

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianSeedTool-iOS#84]
In Ethereum, the `m/44'/60'/0'/0/0` derivation becomes the identifier for the various tools that watch contracts like NFTs.

For instance, if you enter the DPAL demo seed of `fly mule excess resource treat plunge nose soda reflect adult ramp planet` into the iOS metamask wallet, the resulting "Account 1" is `0x557525d043656e9385D8EFAA9Cd4a3aeAdE01168`. If you also check with Ian Coleman's tool, the DPAL seed for m/44'/60'/0'/0/0 is the same value.

Then if you use a tool that support WalletConnect, like the Rarible NFT wallet, it will show the same account, but only for watching the collectibles you've purchased.

Thus for the ethereum community we should support easily deriving this one address as it is used in so many places. We should probably also make this an example of a `crypto-request` and see if we can get the ethereum community to support it.

**Comment by ChristopherA** [comment]
See https://rarible.com/dpal

**Comment by wolfmcnally** [comment]
I believe this to be fixed in the latest release of Gordian Seed Tool.
