### ISSUE TITLE
Both ByteWords & BIP39 wrapping layout on Print

### ISSUE THREAD

**Issue by artk47** [BlockchainCommons/GordianSeedTool-iOS#85]
![image](https://user-images.githubusercontent.com/8707649/130329307-b6039507-df2e-4cb8-8c1e-f1d5b8ec507b.jpeg)

Technically not critical, but missing BIP39 words looks frightening on a somatic level, especially for newbies

**Comment by ChristopherA** [comment]
Thanks for the report. We’ll investigate. We have an new update submitted so the bug still might be in that release. 

Does it print properly? It could be the screen rendering is the only place the bug is.

And of course, a warning not to use that seed as it shared here.

**Comment by wolfmcnally** [comment]
This isn't happening in the latest beta builds of 1.2. So when 1.2 comes out it should be fixed. Please file another issue if it persists after that.

![image](https://user-images.githubusercontent.com/676176/130331486-3e32ab51-9124-4396-9331-414a23911505.png)
