### ISSUE TITLE
FEATURE: SSKR Cover Page

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianSeedTool-iOS#88]
I'd like to see the option of a cover page that offers some instructions on the specific scenario that the user chose for this particular sharding, the ability to add notes and a personal list of who received, and maybe the shard identifiers that are in the sidebar.

Possible targets 1.5 or 1.6

Also related to #87.

**Comment by wolfmcnally** [comment]
Fixed as of 1.3.3 (47).
