### ISSUE TITLE
Add shard metadata as name?

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianSeedTool-iOS#90]
To facilitate requests for the recovery of a shard, maybe we should recommend the default name for a shard when storing it be the bolded words, like "puff wall keys kept". 

This is more of a UX documentation request, but at some point should be in future QR Tool or if we support SSKR shard storage in other apps.

**Comment by wolfmcnally** [comment]
We've started referring to SSKR shards by the last four ByteWords, which is the CRC-32 of the shard itself.
