### ISSUE TITLE
CRITICAL: Mnemonics in PDFs still intermittently being ellipsized and lost.

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianSeedTool-iOS#91]
In 1.2(29): Though the test key "Dark Purple Aqua Love" does not ellipsize and BIP-39 or byte word mnemonics in the printed PDF backup, this bug is still happening (closed in issue #85) with some other test seeds I am trying to backup (BTW, on waterproof paper). 18 bytewords are showing before the … cuts off, but only 6 BIP-39 mnemonics are visible.

I have cut out most of the words as there is a balance on this account, but you can see what is happening. I can share with you the actual problematic seed over Signal. 

![Screen Shot 2021-09-09 at 5 25 35 PM](https://user-images.githubusercontent.com/69103/132779603-8e3f7d70-f2a9-4238-9491-e880d1dd8024.jpg)

**Comment by wolfmcnally** [comment]
Please do.

**Comment by ChristopherA** [comment]
Sent via Signal, plus a second example.

**Comment by wolfmcnally** [comment]
Fixed in 1.2.1 (30).
