### ISSUE TITLE
FEATURE: Add BTC Fingerprint & ETH Account to backup printout

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianSeedTool-iOS#95]
For convenience when puzzling out which seed is needed to restore for which accounts, add the BTC master fingerprint and the ETH #0 account to the bottom of printout

For the DPAL test seed:

Bitcoin Master Key Fingerprint: 604b93f2
Ethereum Account #0 Address [m/44'/60’/0’/0/0]: 0x557525d043656e9385D8EFAA9Cd4a3aeAdE01168

**Comment by wolfmcnally** [comment]
Fixed.
