### ISSUE TITLE
UX: Option to print meta data at top of SSKR Coupon

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianSeedTool-iOS#96]
I'd like to see an option for seed metadata (date, notes, etc.) to appear at the top of the SSKR coupon in the portion the dealer keeps. Alternatively, put on cover page option as per #88.

![image](https://user-images.githubusercontent.com/69103/133000886-0d7ef531-3498-4efb-8802-1d41c6633e31.png)

**Comment by ChristopherA** [comment]
@wolfmcnally This can be closed when you support printing the metadata to the cover page.

**Comment by wolfmcnally** [comment]
This is now supported. Closing.
